apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: rnk-expense
spec:
  selector:
    app: backend
    tier: backend
    project: expense
    version: blue
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080